Application/routes.py
from flask import Blueprint, redirect, request, render_template, url_for, session, flash, current_app, g
from flask_wtf import FlaskForm
import os, base64
from __init__ import db
from models import users, supervisors, staff, questions, staff_responses, supervisor_responses
from forms import DynamicQuestionForm, AddAdminForm, DynamicStaffResponseForm, SignupForm, DynamicSupervisorResponseForm, DynamicPreviewForm, DatabaseForm
from wtforms import TextAreaField, RadioField, SubmitField
from wtforms.validators import DataRequired
from werkzeug.utils import secure_filename
import mysql.connector
from sqlalchemy import create_engine, inspect
import logging

main = Blueprint('main', __name__)

# Landing Page Route

@main.route('/')
def landing():
    form = SignupForm()
    return render_template('login_page.html', form=form)



@main.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        print('cowabanga')
        form = SignupForm()
        print(form.data)

        # for the uploaded picture
        file = form.picture.data
        filename = secure_filename(file.filename)
        file_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)

        if not os.path.exists(current_app.config['UPLOAD_FOLDER']):
                os.makedirs(current_app.config['UPLOAD_FOLDER'])

        file.save(file_path)
        
        # Convert file content to binary
        with open(file_path, 'rb') as f:
            picture_data = f.read()

        new_user = users(
            full_name= form.full_name.data,
            password_hash= form.password.data,
            user_type= form.user_type.data,
            review_period= form.period.data,
            Contact= form.contact.data,
            email= form.email.data,
            picture= picture_data
        )

        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()

        if form.user_type.data == 'Supervisor':
            if form.passkey.data == 'admin101':
               new_job_position = form.spv_position.data
               new_supervisor = supervisors(
                supervisor_id = new_user.user_id,
                job_position=new_job_position
                )
               db.session.add(new_supervisor)
            else:
                 return redirect(url_for('main.landing', message="Invalid passkey"))
        elif form.user_type.data == 'Staff':
            new_job_position = form.staff_job.data
            new_staff = staff(
                staff_id = new_user.user_id,
                job_position=new_job_position
                )
            db.session.add(new_staff)

        db.session.commit()
        return redirect(url_for('main.landing', message="Account created successfully! Login with your account"))
    else:
        return redirect(url_for('main.landing', message="could not create account try loggin in again"))



@main.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['pswd']

        user = users.query.filter_by(email = email).first()
        if user and user.check_password(password):
            session['user_id'] = user.user_id
            session['role'] = user.user_type
            return redirect(url_for('main.homepage'))
        else:
           return redirect(url_for('main.landing', message="Wrong passwrord or ID"))
    else:
     return render_template('login_page.html')



@main.route('/logout', methods=['POST', 'GET'])
def logout():
    session.clear()
    return redirect(url_for('main.landing'))



@main.route('/homepage', methods=['POST', 'GET'])
def homepage():
    user_id = session.get('user_id')
    logged_in_user = users.query.get(user_id)

    print(logged_in_user)
    
    if logged_in_user.user_type == 'Staff':
        staff_user = staff.query.get(user_id)

        jobtitle = staff_user.job_position
    else:
        supervisor_user = supervisors.query.get(user_id)

        jobtitle = supervisor_user.job_position

    return render_template('homepage.html', user=logged_in_user, jobtitle=jobtitle)



@main.route('/add_question', methods=['POST', 'GET'])
def add_question():
    form = DynamicQuestionForm()
    if request.method == 'POST':
        
        if form.add_question_set.data:
            form.question_sets.append_entry()
            
        
        for set_form in form.question_sets:
            if set_form.add_question.data:
                set_form.questions.append_entry()
                
        
        if form.submit.data:

            for set_form in form.question_sets:
                question_title = set_form.question_title.data
                for question_form in set_form.questions:
                    question_text = question_form.question_text.data
                    question_type = question_form.question_type.data
                    
                    
                    new_question = questions(
                        question_title=question_title,
                        question_text=question_text,
                        question_type=question_type
                    )
                    db.session.add(new_question)
                    db.session.commit()
            flash('Questions added successfully!', 'success')
            return redirect(url_for('main.add_question'))
   
    userType = session.get('role')
    if userType == 'Staff':
       flash('You need to be an administrator to access this page')
       return redirect(url_for('main.homepage'))
    else:
         return render_template('Question-setting.html', form=form)

    




@main.route('/form', methods=['POST', 'GET'])
def questions_view():
    question_data = (
        db.session.query(
            questions.question_title,
            questions.question_id,
            questions.question_text,
            questions.question_type
        )
        .order_by(questions.question_id.asc())
        .all()
    )

    print(question_data)
    for question in question_data:
        question_id = question[1]
        if question[3] == 'text':
            print("condition one is being executed")
            setattr(DynamicStaffResponseForm, f'staff_response_{question_id}', TextAreaField('Staff Response', validators=[DataRequired()]))
            #setattr(DynamicStaffResponseForm, f'admin_response_{question_id}', TextAreaField('Admin Response', validators=[DataRequired()]))
        else:
            print("condition two is being executed")
            setattr(DynamicStaffResponseForm, f'staff_scale_{question_id}', RadioField('Staff Scale', choices=[('poor', '1'), ('fair', '2'), ('good', '3'), ('best', '4')], default=None))
            #setattr(DynamicStaffResponseForm, f'admin_scale_{question_id}', RadioField('Admin Scale', choices=[('poor', '1'), ('fair', '2'), ('good', '3'), ('best', '4')], validators=[DataRequired()]))
            setattr(DynamicStaffResponseForm, f'staff_comment_{question_id}', TextAreaField('Staff Comment', validators=[DataRequired()]))
            #setattr(DynamicStaffResponseForm, f'admin_comment_{question_id}', TextAreaField('Admin Comment', validators=[DataRequired()]))

    form = DynamicStaffResponseForm(request.form)

    if request.method == 'POST':
        user_id = session.get('user_id')
    
        if user_id:
        # Query the database to get the user's email
         user = users.query.filter_by(user_id=user_id).first()
        if user:
            email = user.email
        else:
            email = None
            print('User not found.')

        # the body of the email to be sent

        #email_data = ' Thank you for submitting your respoonse you\'ll be notified when your supervisor reviews it'

        for question in question_data:
            question_id = question[1]
            staff_response = request.form.get(f'staff_response_{question_id}')
            #admin_response = request.form.get(f'admin_response_{question_id}')
            staff_scale = request.form.get(f'staff_scale_{question_id}')
            #admin_scale = request.form.get(f'admin_scale_{question_id}')
            staff_comment = request.form.get(f'staff_comment_{question_id}')
            #admin_comment = request.form.get(f'admin_comment_{question_id}')

            if staff_response or staff_scale is not None:
                new_staff_response = staff_responses(
                    staff_id=user_id,
                    question_id=question_id,
                    response_text=staff_response,
                    response_rating=staff_scale,
                    comment = staff_comment
                )
                db.session.add(new_staff_response)

            #if admin_comment or admin_scale is not None:
             #   new_admin_response = supervisor_responses(
              #      supervisor_id=user_id,
               #     question_id=question_id,
                #    comment = admin_comment,
                 #   response_rating=admin_scale,
                
                #)
                #db.session.add(new_admin_response)

        db.session.commit()

        # sending the email to show a preview of what the user has filled.

        #send_form_email(email, email_data)

        flash('Thank you for filling the form, it has been submitted successfully!!', 'success')
        return redirect(url_for('main.homepage'))

    return render_template('form.html', question_data=question_data, form=form)



@main.route('/return_to_form')
def form_return():
    pass
    #previous_form_data = 



@main.route('/return_to_homepage')
def home_return():
    return redirect(url_for('main.homepage'))



@main.route('/manage_admins', methods=['POST', 'GET'])
def add_admin():
    form = AddAdminForm()
    if request.method == "POST":
            new_admin_email = request.form.get('new_admin_email')

            user = users.query.filter_by(email=new_admin_email ).first()
            if form.add_admin.data:

Application/templates/Question-setting.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms.css')}}">
{% endblock %}
{% block content %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div id="flash-messages">
                {% for category, message in messages %}
                    <div class="flash-messages">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    <form method="POST">
        <h1>Add Questions</h1>
        {{ form.hidden_tag() }}
        {% for set_form in form.question_sets %}
            <div class="question-set">
                    <div class="set-title">
                        {{ set_form.question_title.label }}<br>
                        {{ set_form.question_title (class="text_inputs") }}
                    </div>
                    <br>  
                <div class="questions">
                    {% for question_form in set_form.questions %}
                        <div class="question">
                            {{ question_form.hidden_tag() }}
                            {{ question_form.question_type.label }}<br>
                            {{ question_form.question_type (class="text_inputs")}}<br>
                            <br>
                            {{ question_form.question_text.label }}<br>
                            {{ question_form.question_text }}
                        </div>
                    {% endfor %}
                </div>
                <br>
                {{ set_form.add_question (class="button") }}
            </div>
        {% endfor %}
        {{ form.add_question_set (class="button") }}<br>
        {{ form.submit (class="button") }}
        <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
    </form>
{% endblock content %}

Application/templates/add_admin.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms2.css')}}">
{% endblock %}
{% block content %}
<form method="POST" action= "{{ url_for( 'main.add_admin') }}" >
    {{ form.hidden_tag() }}

   <h1> Manage Administrators </h1>

   <div id="massage"> 
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div id="flash-messages">
            {% for category, message in messages %}
                <div class="flash-message {{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
    </div>

   {{ form.new_admin_email.label}}<br>
   {{ form.new_admin_email }}<br>
   <br>
   {{ form.add_admin  (class="button")  }}   {{ form.remove_admin  (class="button")  }}<br>
<br>
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>
{% endblock content %}

Application/templates/database.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms2.css')}}">
<style>
.question_set{
    justify-items: center;
    margin: 0 0 10px 0;
    padding: 10px;
}

</style>
{% endblock %}
{% block content %}
<form method="POST" action= "{{ url_for( 'main.add_admin') }}" >


   <h1> Manage Database </h1>

   
    <div class="question_set">
        <h2 style = "font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Create Database</h2>
        <a href = "{{ url_for( 'main.create_database') }}"><button type="button" style = "float:none;" >Create</button></a>
    </div>
    <div class="question_set">
        <h2 style = "font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">Switch Database</h2>
        <a href = "{{ url_for( 'main.switch_database') }}"><button type="button" style = "float:none;" >Switch</button></a>
    </div>
    <br>
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button" >Back</button></a>
</form>


<div id="massage"> 
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div id="flash-messages">
            {% for category, message in messages %}
                <div class="flash-message {{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
    </div>
    
{% endblock content %}

Application/templates/form.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms.css')}}">
{% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('main.questions_view') }}">
    {{ form.hidden_tag() }}

    {% set printed_titles = [] %}
    {% for question in question_data %}
        {% if question[0] not in printed_titles %}
            <h1>{{ question[0] }}</h1>
            {% set _ = printed_titles.append(question[0]) %}
        {% endif %}
        <div class="question_set">
            <p>{{ question[2] }}</p>

            {% if question[3] == 'text' %}

                {{ form['staff_response_' ~ question[1]] }}

            {% else %}

            <p> Self evaluation</p>

                {{ form['staff_scale_' ~ question[1]] (class="radio_button") }}
                
            <p> Comment</p>
                {{ form['staff_comment_' ~ question[1]]  }}
            
            {% endif %}
        </div>
    {% endfor %}

    {{ form.submit (class="button") }}
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>
{% endblock content %}

Application/templates/form_review_list.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/review.css')}}">
{% endblock %}

{% block content %}

<table>
    <tr>
        <th>ID</th>
        <th>Staff Name</th>

    </tr>
    {% if position == "Operational Manager"%}
        {% for staff in staffs %}
          {% for user in staff_user %}
             {% if user.user_id == staff.staff_id and staff.job_position == "Staff 1" %}
    <tr>
        <td>{{ staff.staff_id }}</td>
        <td><a href="{{ url_for('main.review_form', staff_id=staff.staff_id) }}">{{ user.full_name}}</a></td>

    </tr>
             {% endif %}
         {% endfor %}   
        {% endfor %}

    {% elif position == "Principal"%}
        {% for staff in staffs %}
          {% for user in staff_user %}
             {% if staff.job_position == "Staff 2" and user.user_id == staff.staff_id %}
    <tr>
        <td>{{ staff.staff_id }}</td>
        <td><a href="{{url_for('main.review_form', staff_id=staff.staff_id)}}">{{ user.full_name}}</a></td>
       
    </tr>
             {% endif %}
         {% endfor %}   
        {% endfor %}

    {% elif position == "Director"%}
        {% for staff in staffs %}
          {% for user in staff_user %}
             {% if staff.job_position == "Staff 3" and user.user_id == staff.staff_id %}
    <tr>
        <td>{{ staff.staff_id }}</td>
        <td><a href="{{url_for('main.review_form', staff_id=staff.staff_id)}}">{{ user.full_name}}</a></td>

    </tr>
             {% endif %}
         {% endfor %}   
        {% endfor %}


    {% endif %}

</table>
<div id="massage"> 
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
            {% for category, message in messages %}
                    {{ message }}
            {% endfor %}
    {% endif %}
    {% endwith %}
</div>

<a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>



{% endblock content%}

Application/templates/homepage.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/homepage.css')}}">
{% endblock %}
{% block content %}

<nav class="nav1">
    <img id="school_logo" src="../static/images/hopac logo.jpg" alt="school logo">
    <h1> Perfomance feedback and goal setting</h1>
    <input type="checkbox" id="check">
    <label for="check" class="menu">
    <i class="fa-solid fa-bars"></i>
    </label>
</nav>


<div class="menu_list" id="menuList">
    <ul>
        <li><a href="{{ url_for( 'main.logout' ) }}">Logout</a></li>
        <li><a href="{{ url_for( 'main.logout' ) }}">Item 1</a></li>
        <li><a href="{{ url_for( 'main.logout' ) }}">Item 2</a></li>
        <li><a href="{{ url_for( 'main.logout' ) }}">Item 3</a></li>
        <li><a href="{{ url_for( 'main.logout' ) }}">Item 4</a></li>
    </ul>
</div>
<div id="massage"> 
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
            {% for category, message in messages %}
                    {{ message }}
            {% endfor %}
    {% endif %}
    {% endwith %}
</div>



<div class="container" id="main">
   
    <nav class="nav2">
        <ul>
            <li><button class="navButtons" id="profile">Profile</button></li>
            <li><button class="navButtons" id="evaluation_form">Evaluation Form</button></li>
            <li><button class="navButtons" id="admin_panel">Admin Panel</button></li>
            <li><button class="navButtons" id="dashboard">Dashboard</button></li>
            <li><button class="navButtons" id="help_center">Help center</button></li>
        </ul>
    </nav>
    <div class="profile">
        <div class="passport">
            {% if user.picture %}
            <img src="data:image/jpeg;base64,{{ user.picture|b64encode }}" alt="Profile Picture" >
            {% else %}
            <h5>No profile picture uploaded</h5>
            {% endif %}
        </div>
        <div class="usr_description">
          <p class="label">Name</p>
          <p class="usr_info" id="usr_name">{{ user.full_name }}</p><br>
          <p class="label">Position</p>
          <p class="usr_info" id="usr_pstn">{{ user.user_type }}</p><br>
          <p class="label">Jobtitle</p>
          <p class="usr_info" id="usr_jobtitle">{{ jobtitle }}</p><br>
       </div>
  </div>
    <div class="evaluation_form">
        <div class="in_descriptions">
        <h3> Press the button to start filling your evaluation form</h3>
        <a href="{{ url_for( 'main.questions_view') }}"> <button class="min_button">Go to form</button></a>
        </div>
        <div class="in_descriptions">
            <h3> Press the button to check the review for your form</h3>
            <a href="{{ url_for( 'main.staff_form_review', staff_id=user.user_id) }}"> <button class="min_button">Check form</button></a>
            </div>
        {% if user.user_type == 'Supervisor' %}
        <div class="in_descriptions">
            <h3>Press the button to review and give your feedback to forms</h3>
            <a href="{{ url_for( 'main.review_form_list') }}"><button class ="min_button">Give feedback to forms</button></a>
        </div>
        {% endif %}
    </div>
    
    <div class="admin_panel" id="admin">
        <div class="in_descriptions">
        <h3>Set this years questions</h3>
        <a href="{{ url_for( 'main.add_question') }}"><button class='min_button' type="button">Set questions</button></a>
        </div>
        <div class="in_descriptions">
        <h3>Give administrative authority</h3>
        <a href = "{{ url_for( 'main.add_admin') }}"><button class='min_button' id="admin_add_button">Add administrator</button></a>
        </div>
        <div class="in_descriptions">
        <h3>Preview set questions</h3>
        <a href = "{{ url_for( 'main.form_preview') }}"><button class='min_button' id="preview_button">Preview questions</button></a>
         </div>
         <div class="in_descriptions">
        <h3>Manage Database</h3>
        <a href = "{{ url_for( 'main.manage_database') }}"><button class='min_button' id="preview_button">Manage Database</button></a>
         </div>
    </div>
    <div class="dashboard"></div>
    <div class="help_center"></div>

</div>


<script>

    const main = document.getElementById('main');
    const dashboardButton = document.getElementById('dashboard');
    const evaluationButton = document.getElementById('evaluation_form');
    const adminButton = document.getElementById('admin_panel');
    const profileButton = document.getElementById('profile');
    const helpButton = document.getElementById('help_center');


    dashboardButton.addEventListener('click', () => {
        main.classList.remove("evaluationform_active");
        main.classList.remove("adminpanel_active");
        main.classList.remove("helpcenter_active");
        main.classList.add("dashboard_active");
    });
    evaluationButton.addEventListener('click', () => {
        main.classList.remove("adminpanel_active");
        main.classList.remove("dashboard_active");
        main.classList.remove("helpcenter_active");
        main.classList.add("evaluationform_active");
    });
    adminButton.addEventListener('click', () => {
        main.classList.remove("evaluationform_active");
        main.classList.remove("dashboard_active");
        main.classList.remove("helpcenter_active");
        main.classList.add("adminpanel_active");
    });
    profileButton.addEventListener('click', () => {
        main.classList.remove("evaluationform_active");
        main.classList.remove("adminpanel_active");
        main.classList.remove("helpcenter_active");
        main.classList.remove("dashboard_active");
    });
    helpButton.addEventListener('click', () => {
        main.classList.remove("evaluationform_active");
        main.classList.remove("adminpanel_active");
        main.classList.remove("dashboard_active");
        main.classList.add("helpcenter_active");
    });

    document.getElementById('check').addEventListener('change', function() {
        var menuList = document.getElementById('menuList');
        if (this.checked) {
        menuList.style.transform = 'translateX(0)';
        } else {
        menuList.style.transform = 'translateX(100%)';
        }
    });

// This is to control the administrators panel actions when adding an admin
    const add_adminButton = document.getElementById('admin_add_button');
    const return_from_newAdminButton = document.getElementById('return_from_newAdmin');

    add_adminButton.addEventListener('click', () => {
        adminpanel.classList.add("adding_admin");
    });
    return_from_newAdminButton.addEventListener('click', () => {
        adminpanel.classList.remove("adding_admin");
    });

   
</script>

{% endblock content %}

Application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Hopacweb - {{title}}</title>
    {% else %}
    <title> Hopacweb</title>
    {% endif %}
    {% block css %}{% endblock %}
    <script src="https://kit.fontawesome.com/395a842d27.js" crossorigin="anonymous"></script>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

Application/templates/manage_admins.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms2.css')}}">
{% endblock %}
{% block content %}
<form method="POST" action= "{{ url_for( 'main.add_admin') }}" >
    {{ form.hidden_tag() }}

   <h1> Manage Administrators </h1>

   

   {{ form.new_admin_email.label}}<br>
   {{ form.new_admin_email }}<br>
   <br>
   {{ form.add_admin  (class="button")  }} <br>
<br>
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>

<div id="massage"> 
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div id="flash-messages">
            {% for category, message in messages %}
                <div class="flash-message {{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% endwith %}
    </div>
{% endblock content %}

Application/templates/preview.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms.css')}}">
{% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('main.form_preview') }}">
    {{ form.hidden_tag() }}

    {% set printed_titles = [] %}
    {% for question in question_data %}
        {% if question[0] not in printed_titles %}
            <h1>{{ question[0] }}</h1>
            {% set _ = printed_titles.append(question[0]) %}
        {% endif %}
        <div class="question_set">
            <a href="{{ url_for('main.remove_question', question_id = question[1]) }}"><button type="button">Remove Question</button></a>
            <p>{{ question[2] }}</p>           
            {% if question[3] == 'text' %}

                {{ form['staff_response_' ~ question[1]] (readonly=True)}}
                
            {% else %}
               <p> Self evaluation</p>

                {{ form['staff_scale_' ~ question[1]] (class="radio_button", readonly=True) }}

               <p> Comment</p>

                {{ form['staff_comment_' ~ question[1]] (readonly=True) }}
            
            {% endif %}
        </div>
    {% endfor %}

    {{ form.submit (class="button") }}
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>
{% endblock content %}

Application/templates/review_form.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms.css')}}">
{% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('main.review_form', staff_id=staff_member.user_id) }}">
    {{ form.hidden_tag() }}
    <div class="owner_title">
        <p>This form was filled by {{staff_member.full_name}}</p>
    </div>
    {% set printed_titles = [] %}
    {% for question in question_data %}
        {% if question[0] not in printed_titles %}
            <h1>{{ question[0] }}</h1>
            {% set _ = printed_titles.append(question[0]) %}
        {% endif %}
        
        <div class="question_set">
            <p>{{ question[3] }}</p>
            {% if question[4] == 'text' %}
              {% for response in staff_response %}
                {% if response.question_id == question[1] %}
                    <p>{{response.response_text}}</p>
                {% endif %}
               {% endfor %}
            {% else %}
            <p> Self evaluation</p>
                {% for response in staff_response %}
                    {% if response.question_id == question[1] %}
                        <p>I evaluate myself to be {{response.response_rating}} at my perfomance</p>
            <p> Comment:</p>
                        <p>{{response.comment}}</p>
                    {% endif %}
                {% endfor %}
            <p>Supervisor's evaluation</p>
                {{ form['admin_scale_' ~ question[1]] (class="radio_button") }}
            <p> Comment:</p>
                {{ form['admin_comment_' ~ question[1]] }}
            {% endif %}
        </div>
    {% endfor %}

    {{ form.submit (class="button") }}
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>
{% endblock content %}

Application/templates/staff_form_review.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/forms.css')}}">
{% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('main.staff_form_review', staff_id=staff_member.user_id) }}">
    

    {% set printed_titles = [] %}
    {% for question in question_data %}
        {% if question[0] not in printed_titles %}
            <h1>{{ question[0] }}</h1>
            {% set _ = printed_titles.append(question[0]) %}
        {% endif %}
        
        <div class="question_set">
            <p>{{ question[2] }}</p>
            {% if question[3] == 'text' %}
              {% for response in staff_response %}
                {% if response.question_id == question[1] %}
                    <p>{{response.response_text}}</p>
                {% endif %}
               {% endfor %}
            {% else %}
            <p> Self evaluation:</p>
                {% for response in staff_response %}
                    {% if response.question_id == question[1] %}
                        <p>I evaluate myself to be {{response.response_rating}} at my perfomance</p>
            <p> Comment:</p>
                        <p>{{response.comment}}</p>
                        {% endif %}
                {% endfor %}
                    <p>Supervisor's evaluation:</p>
                    {% for review in supervisor_response %}
                        {% if review.question_id == question[1] %}
                           <p>{{review.response_rating}}</p>
                    <p> Comment:</p>
                           <p>{{review.comment}}</p>
                        {% endif %}
                    {% endfor %}
            {% endif %}
                </div>
    {% endfor %}
    <a href = "{{ url_for( 'main.home_return') }}"><button type="button">Back</button></a>
</form>
{% endblock content %}